name: Check code validity

on: [push]

jobs:
  check:
    name: Check code format and TypeScript types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Check files are formatted with Prettier
        run: npx prettier --check README.md CHANGELOG.md CONTRIBUTING.md package.json "packages/**/*.{js,jsx,ts,tsx,md,mdx,json}"
      - name: Check TypeScript typings
        run: |
          cd packages/storybook-addon-designs
          npx tsc --noEmit
